### ISSUE TITLE
Identifying the bootstrap_cluster module

### ISSUE THREAD

**Issue by jeremycfd** [agartland/cycluster#1]
Hi Andrew,

I've been unable to identify the python3 module "bootstrap_cluster" that is called by your initialization script. Could you provide some more details on what you're using here?

Thanks!

**Comment by agartland** [comment]
See, this is why I need a tutorial about installation and use!
That module along with other dependencies may be found in my [utils repo](https://github.com/agartland/utils).
Thanks for working on this with me!

**Comment by jeremycfd** [comment]
Thanks, that did the trick!
